import '../scss/style.scss'
import '../js/swiper-repair-brands'
import '../js/show-brands'
import '../js/show-text'
import '../js/swiper-repair-devices'
import '../js/show-devices'
import '../js/swiper-price-list'
import '../js/burger-menu'
import '../js/show-modal'
console.log('Works!')
